### ISSUE TITLE
default rails environment is production not staging

### ISSUE THREAD

**Issue by vsrboth** [endoze/mina-multistage#25] opened 2016-12-16 03:31 UTC
Kindly find the follow code snippet running using `mina deploy`:

<img width="1429" alt="screen shot 2016-12-16 at 10 31 16 am" src="https://cloud.githubusercontent.com/assets/5484995/21250832/d3984d3e-c37a-11e6-9fdf-ab84b0f242a4.png">

**Comment by jerecui** [comment] 2017-04-20 14:25
mina's multiple env feature:
https://github.com/mina-deploy/mina/blob/2608e50049cf21b1425c8bb7c3e5dd0e964b725f/docs/cookbook.md

**Comment by endoze** [comment] 2017-04-20 19:40
@vsrboth It looks like you are using another plugin with mina for sidekiq. I don't know how that particular plugin is set up, but I don't believe mina-multistage is related to the issue you are having. You should verify you are in fact using mina-multistage and not the built in multiple environment feature of mina. Also that the sidekiq plugin you are using is configured correctly for your environment.

I'm going to close this issue out, but please feel free to re-open if the issue is a result of the mina-multistage gem. Thanks for reporting your issue!

**Closed by endoze** 2017-04-20 19:40 UTC
