### ISSUE TITLE
Empty domain for whenever_name

### ISSUE THREAD

**Issue by shlima** [endoze/mina-multistage#16] opened 2015-12-02 22:00 UTC
I am using  mina/whenver with mine/multistage, the `whenever_name` variable has missing `domain` 

```ruby
set_default :whenever_name, "#{domain}_#{rails_env}" 
```

**Comment by shlima** [comment] 2015-12-02 22:02
setting `set :whenever_name, -> { binding.pry; "#{domain}_#{rails_env}" }` fixed the issue

**Comment by endoze** [comment] 2015-12-03 17:14
@shlima If this issue is resolved, I'm going to mark it as such and close it. If you still seem to have an issue and the cause is in the `mina-multistage` code, re-open the issue and I'd be happy to take a look at it. Thanks for using this gem and contributing :smile:

**Closed by endoze** 2015-12-03 17:14 UTC
